# Generated by Django 4.2.4 on 2023-09-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capital', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=100)),
                ('president', models.CharField(max_length=100)),
            ],
        ),
    ]
